server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/bank_db
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

app:
  jwt-secret: mysecretkeymysecretkeymysecretkey123
  aes-key: 1234567890123456